# SERVER CONFIG
server:
  port: 8080
#  servlet:
#    context-path: /

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest_api_demo?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 1234

  ## Hibernate Properties
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# Hibernate ddl auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
logging:
  file:
    name: logs/development.log # Log files rotate when they reach 10 MB
app:
  message: "This is primary Property for ${spring.application.name} to Dev"
