# SERVER CONFIG
server:
  port: 8080
#  servlet:
#    context-path: /

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest_api_demo?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
    username: root
    password: password

  ## Hibernate Properties
  # The SQL dialect makes Hibernate generate better SQL for the chosen database
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  # Hibernate ddl auto (create, create-drop, validate, update)
          ddl-auto: update

app:
  message: "This is primary Property for ${spring.application.name} to Dev"